# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Template-Default
version:      1.06
version_from: lib/HTML/Template/Default.pm
installdirs:  site
requires:
    Carp:                          0
    HTML::Template:                0
    LEOCHARRE::DEBUG:              1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
